




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace Net_Battle_S2C
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool NotifyEnermyInstantiate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool isSuccess, int uniqueID, int handle, UnityEngine.Vector3 pos, float angle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.NotifyEnermyInstantiate;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, isSuccess);
		Arena_Server.Marshaler.Write(__msg, uniqueID);
		Arena_Server.Marshaler.Write(__msg, handle);
		Arena_Server.Marshaler.Write(__msg, pos);
		Arena_Server.Marshaler.Write(__msg, angle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_NotifyEnermyInstantiate, Common.NotifyEnermyInstantiate);
}

public bool NotifyEnermyInstantiate(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, bool isSuccess, int uniqueID, int handle, UnityEngine.Vector3 pos, float angle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.NotifyEnermyInstantiate;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, isSuccess);
Arena_Server.Marshaler.Write(__msg, uniqueID);
Arena_Server.Marshaler.Write(__msg, handle);
Arena_Server.Marshaler.Write(__msg, pos);
Arena_Server.Marshaler.Write(__msg, angle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_NotifyEnermyInstantiate, Common.NotifyEnermyInstantiate);
}
public bool NotifyEnermyKill(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool isSuccess, int uniqueID, int exp, int gold, string itemArr)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.NotifyEnermyKill;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, isSuccess);
		Arena_Server.Marshaler.Write(__msg, uniqueID);
		Arena_Server.Marshaler.Write(__msg, exp);
		Arena_Server.Marshaler.Write(__msg, gold);
		Arena_Server.Marshaler.Write(__msg, itemArr);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_NotifyEnermyKill, Common.NotifyEnermyKill);
}

public bool NotifyEnermyKill(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, bool isSuccess, int uniqueID, int exp, int gold, string itemArr)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.NotifyEnermyKill;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, isSuccess);
Arena_Server.Marshaler.Write(__msg, uniqueID);
Arena_Server.Marshaler.Write(__msg, exp);
Arena_Server.Marshaler.Write(__msg, gold);
Arena_Server.Marshaler.Write(__msg, itemArr);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_NotifyEnermyKill, Common.NotifyEnermyKill);
}
public bool NotifyGetReword(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool isSuccess, Nettention.Proud.HostID getID, int uniqueID)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.NotifyGetReword;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, isSuccess);
		Arena_Server.Marshaler.Write(__msg, getID);
		Arena_Server.Marshaler.Write(__msg, uniqueID);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_NotifyGetReword, Common.NotifyGetReword);
}

public bool NotifyGetReword(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, bool isSuccess, Nettention.Proud.HostID getID, int uniqueID)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.NotifyGetReword;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, isSuccess);
Arena_Server.Marshaler.Write(__msg, getID);
Arena_Server.Marshaler.Write(__msg, uniqueID);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_NotifyGetReword, Common.NotifyGetReword);
}
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_NotifyEnermyInstantiate="NotifyEnermyInstantiate";
public const string RmiName_NotifyEnermyKill="NotifyEnermyKill";
public const string RmiName_NotifyGetReword="NotifyGetReword";
       
public const string RmiName_First = RmiName_NotifyEnermyInstantiate;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_NotifyEnermyInstantiate="";
public const string RmiName_NotifyEnermyKill="";
public const string RmiName_NotifyGetReword="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

