 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace Net_Battle_C2S
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RequestEnermyInstantiate = (Nettention.Proud.RmiID)500+1;
			public const Nettention.Proud.RmiID RequestEnermyKill = (Nettention.Proud.RmiID)500+2;
			public const Nettention.Proud.RmiID RequestGetReword = (Nettention.Proud.RmiID)500+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RequestEnermyInstantiate,
			RequestEnermyKill,
			RequestGetReword,
		};
	}
}

				 
