




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace DB_Account_C2S
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool RequestConnectServer(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string id)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestConnectServer;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, id);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestConnectServer, Common.RequestConnectServer);
}

public bool RequestConnectServer(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string id)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestConnectServer;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, id);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestConnectServer, Common.RequestConnectServer);
}
public bool RequestCreateCharacter(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string id, string name, int handle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestCreateCharacter;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, id);
		Arena_Server.Marshaler.Write(__msg, name);
		Arena_Server.Marshaler.Write(__msg, handle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestCreateCharacter, Common.RequestCreateCharacter);
}

public bool RequestCreateCharacter(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string id, string name, int handle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestCreateCharacter;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, id);
Arena_Server.Marshaler.Write(__msg, name);
Arena_Server.Marshaler.Write(__msg, handle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestCreateCharacter, Common.RequestCreateCharacter);
}
public bool RequestPlayerCharactersInformation(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestPlayerCharactersInformation;
		__msg.Write(__msgid);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestPlayerCharactersInformation, Common.RequestPlayerCharactersInformation);
}

public bool RequestPlayerCharactersInformation(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestPlayerCharactersInformation;
__msg.Write(__msgid);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestPlayerCharactersInformation, Common.RequestPlayerCharactersInformation);
}
public bool RequestDeleteCharacter(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string id, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestDeleteCharacter;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, id);
		Arena_Server.Marshaler.Write(__msg, name);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestDeleteCharacter, Common.RequestDeleteCharacter);
}

public bool RequestDeleteCharacter(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string id, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestDeleteCharacter;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, id);
Arena_Server.Marshaler.Write(__msg, name);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestDeleteCharacter, Common.RequestDeleteCharacter);
}
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_RequestConnectServer="RequestConnectServer";
public const string RmiName_RequestCreateCharacter="RequestCreateCharacter";
public const string RmiName_RequestPlayerCharactersInformation="RequestPlayerCharactersInformation";
public const string RmiName_RequestDeleteCharacter="RequestDeleteCharacter";
       
public const string RmiName_First = RmiName_RequestConnectServer;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_RequestConnectServer="";
public const string RmiName_RequestCreateCharacter="";
public const string RmiName_RequestPlayerCharactersInformation="";
public const string RmiName_RequestDeleteCharacter="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}
namespace DB_Information_C2S
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool RequestGetPlayerStorage(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestGetPlayerStorage;
		__msg.Write(__msgid);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestGetPlayerStorage, Common.RequestGetPlayerStorage);
}

public bool RequestGetPlayerStorage(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestGetPlayerStorage;
__msg.Write(__msgid);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestGetPlayerStorage, Common.RequestGetPlayerStorage);
}
public bool RequestGetCharacter(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestGetCharacter;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, name);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestGetCharacter, Common.RequestGetCharacter);
}

public bool RequestGetCharacter(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestGetCharacter;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, name);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestGetCharacter, Common.RequestGetCharacter);
}
public bool RequestGetCharacterEquipment(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestGetCharacterEquipment;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, name);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestGetCharacterEquipment, Common.RequestGetCharacterEquipment);
}

public bool RequestGetCharacterEquipment(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestGetCharacterEquipment;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, name);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestGetCharacterEquipment, Common.RequestGetCharacterEquipment);
}
public bool RequestGetCharacterInventory(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestGetCharacterInventory;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, name);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestGetCharacterInventory, Common.RequestGetCharacterInventory);
}

public bool RequestGetCharacterInventory(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestGetCharacterInventory;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, name);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestGetCharacterInventory, Common.RequestGetCharacterInventory);
}
public bool RequestGetCharacterQuest(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestGetCharacterQuest;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, name);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestGetCharacterQuest, Common.RequestGetCharacterQuest);
}

public bool RequestGetCharacterQuest(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestGetCharacterQuest;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, name);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestGetCharacterQuest, Common.RequestGetCharacterQuest);
}
public bool RequestGetCharacterSkill(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestGetCharacterSkill;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, name);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestGetCharacterSkill, Common.RequestGetCharacterSkill);
}

public bool RequestGetCharacterSkill(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestGetCharacterSkill;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, name);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestGetCharacterSkill, Common.RequestGetCharacterSkill);
}
public bool RequestGetQuickSlot(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestGetQuickSlot;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, name);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestGetQuickSlot, Common.RequestGetQuickSlot);
}

public bool RequestGetQuickSlot(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string name)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestGetQuickSlot;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, name);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestGetQuickSlot, Common.RequestGetQuickSlot);
}
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_RequestGetPlayerStorage="RequestGetPlayerStorage";
public const string RmiName_RequestGetCharacter="RequestGetCharacter";
public const string RmiName_RequestGetCharacterEquipment="RequestGetCharacterEquipment";
public const string RmiName_RequestGetCharacterInventory="RequestGetCharacterInventory";
public const string RmiName_RequestGetCharacterQuest="RequestGetCharacterQuest";
public const string RmiName_RequestGetCharacterSkill="RequestGetCharacterSkill";
public const string RmiName_RequestGetQuickSlot="RequestGetQuickSlot";
       
public const string RmiName_First = RmiName_RequestGetPlayerStorage;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_RequestGetPlayerStorage="";
public const string RmiName_RequestGetCharacter="";
public const string RmiName_RequestGetCharacterEquipment="";
public const string RmiName_RequestGetCharacterInventory="";
public const string RmiName_RequestGetCharacterQuest="";
public const string RmiName_RequestGetCharacterSkill="";
public const string RmiName_RequestGetQuickSlot="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}
namespace DB_Alter_C2S
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool RequestItemBuy(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int itemHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemBuy;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, itemHandle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemBuy, Common.RequestItemBuy);
}

public bool RequestItemBuy(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int itemHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemBuy;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, itemHandle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemBuy, Common.RequestItemBuy);
}
public bool RequestItemBuyNumber(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int itemHandle, int number)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemBuyNumber;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, itemHandle);
		Arena_Server.Marshaler.Write(__msg, number);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemBuyNumber, Common.RequestItemBuyNumber);
}

public bool RequestItemBuyNumber(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int itemHandle, int number)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemBuyNumber;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, itemHandle);
Arena_Server.Marshaler.Write(__msg, number);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemBuyNumber, Common.RequestItemBuyNumber);
}
public bool RequestItemUse(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int itemHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemUse;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, itemHandle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemUse, Common.RequestItemUse);
}

public bool RequestItemUse(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int itemHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemUse;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, itemHandle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemUse, Common.RequestItemUse);
}
public bool RequestItemEquip(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int inventoryNum)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemEquip;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, inventoryNum);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemEquip, Common.RequestItemEquip);
}

public bool RequestItemEquip(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int inventoryNum)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemEquip;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, inventoryNum);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemEquip, Common.RequestItemEquip);
}
public bool RequestItemUnEquip(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, EItemType itemType)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemUnEquip;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, itemType);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemUnEquip, Common.RequestItemUnEquip);
}

public bool RequestItemUnEquip(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, EItemType itemType)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemUnEquip;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, itemType);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemUnEquip, Common.RequestItemUnEquip);
}
public bool RequestItemDelete(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int inventoryNum)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemDelete;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, inventoryNum);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemDelete, Common.RequestItemDelete);
}

public bool RequestItemDelete(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int inventoryNum)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemDelete;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, inventoryNum);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemDelete, Common.RequestItemDelete);
}
public bool RequestItemDeleteNumber(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int inventoryNum, int number)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemDeleteNumber;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, inventoryNum);
		Arena_Server.Marshaler.Write(__msg, number);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemDeleteNumber, Common.RequestItemDeleteNumber);
}

public bool RequestItemDeleteNumber(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int inventoryNum, int number)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemDeleteNumber;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, inventoryNum);
Arena_Server.Marshaler.Write(__msg, number);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemDeleteNumber, Common.RequestItemDeleteNumber);
}
public bool RequestItemSell(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int inventoryNum)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemSell;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, inventoryNum);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemSell, Common.RequestItemSell);
}

public bool RequestItemSell(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int inventoryNum)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemSell;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, inventoryNum);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemSell, Common.RequestItemSell);
}
public bool RequestItemSellNumber(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int inventoryNum, int number)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemSellNumber;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, inventoryNum);
		Arena_Server.Marshaler.Write(__msg, number);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemSellNumber, Common.RequestItemSellNumber);
}

public bool RequestItemSellNumber(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int inventoryNum, int number)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemSellNumber;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, inventoryNum);
Arena_Server.Marshaler.Write(__msg, number);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemSellNumber, Common.RequestItemSellNumber);
}
public bool RequestItemProduce(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int handle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestItemProduce;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, handle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestItemProduce, Common.RequestItemProduce);
}

public bool RequestItemProduce(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int handle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestItemProduce;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, handle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestItemProduce, Common.RequestItemProduce);
}
public bool RequestInvenvorySort(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestInvenvorySort;
		__msg.Write(__msgid);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestInvenvorySort, Common.RequestInvenvorySort);
}

public bool RequestInvenvorySort(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestInvenvorySort;
__msg.Write(__msgid);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestInvenvorySort, Common.RequestInvenvorySort);
}
public bool RequestQuestAccept(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int questHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestQuestAccept;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, questHandle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestQuestAccept, Common.RequestQuestAccept);
}

public bool RequestQuestAccept(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int questHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestQuestAccept;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, questHandle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestQuestAccept, Common.RequestQuestAccept);
}
public bool RequestQuestDelete(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int questHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestQuestDelete;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, questHandle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestQuestDelete, Common.RequestQuestDelete);
}

public bool RequestQuestDelete(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int questHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestQuestDelete;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, questHandle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestQuestDelete, Common.RequestQuestDelete);
}
public bool RequestQuestClear(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int questHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestQuestClear;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, questHandle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestQuestClear, Common.RequestQuestClear);
}

public bool RequestQuestClear(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int questHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestQuestClear;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, questHandle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestQuestClear, Common.RequestQuestClear);
}
public bool RequestStatusUseStatPoint(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, EStatType type)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestStatusUseStatPoint;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, type);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestStatusUseStatPoint, Common.RequestStatusUseStatPoint);
}

public bool RequestStatusUseStatPoint(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, EStatType type)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestStatusUseStatPoint;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, type);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestStatusUseStatPoint, Common.RequestStatusUseStatPoint);
}
public bool RequestStatusUseSkillPoint(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int skillHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestStatusUseSkillPoint;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, skillHandle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestStatusUseSkillPoint, Common.RequestStatusUseSkillPoint);
}

public bool RequestStatusUseSkillPoint(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int skillHandle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestStatusUseSkillPoint;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, skillHandle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestStatusUseSkillPoint, Common.RequestStatusUseSkillPoint);
}
public bool RequestDeleteQuickSlot(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int number)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestDeleteQuickSlot;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, number);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestDeleteQuickSlot, Common.RequestDeleteQuickSlot);
}

public bool RequestDeleteQuickSlot(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int number)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestDeleteQuickSlot;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, number);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestDeleteQuickSlot, Common.RequestDeleteQuickSlot);
}
public bool RequestSetQuickSlot(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int number, bool isItem, int handle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestSetQuickSlot;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, number);
		Arena_Server.Marshaler.Write(__msg, isItem);
		Arena_Server.Marshaler.Write(__msg, handle);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestSetQuickSlot, Common.RequestSetQuickSlot);
}

public bool RequestSetQuickSlot(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int number, bool isItem, int handle)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestSetQuickSlot;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, number);
Arena_Server.Marshaler.Write(__msg, isItem);
Arena_Server.Marshaler.Write(__msg, handle);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestSetQuickSlot, Common.RequestSetQuickSlot);
}
public bool RequestGetCoupon(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int handle, int value)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestGetCoupon;
		__msg.Write(__msgid);
		Arena_Server.Marshaler.Write(__msg, handle);
		Arena_Server.Marshaler.Write(__msg, value);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestGetCoupon, Common.RequestGetCoupon);
}

public bool RequestGetCoupon(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int handle, int value)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestGetCoupon;
__msg.Write(__msgid);
Arena_Server.Marshaler.Write(__msg, handle);
Arena_Server.Marshaler.Write(__msg, value);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestGetCoupon, Common.RequestGetCoupon);
}
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_RequestItemBuy="RequestItemBuy";
public const string RmiName_RequestItemBuyNumber="RequestItemBuyNumber";
public const string RmiName_RequestItemUse="RequestItemUse";
public const string RmiName_RequestItemEquip="RequestItemEquip";
public const string RmiName_RequestItemUnEquip="RequestItemUnEquip";
public const string RmiName_RequestItemDelete="RequestItemDelete";
public const string RmiName_RequestItemDeleteNumber="RequestItemDeleteNumber";
public const string RmiName_RequestItemSell="RequestItemSell";
public const string RmiName_RequestItemSellNumber="RequestItemSellNumber";
public const string RmiName_RequestItemProduce="RequestItemProduce";
public const string RmiName_RequestInvenvorySort="RequestInvenvorySort";
public const string RmiName_RequestQuestAccept="RequestQuestAccept";
public const string RmiName_RequestQuestDelete="RequestQuestDelete";
public const string RmiName_RequestQuestClear="RequestQuestClear";
public const string RmiName_RequestStatusUseStatPoint="RequestStatusUseStatPoint";
public const string RmiName_RequestStatusUseSkillPoint="RequestStatusUseSkillPoint";
public const string RmiName_RequestDeleteQuickSlot="RequestDeleteQuickSlot";
public const string RmiName_RequestSetQuickSlot="RequestSetQuickSlot";
public const string RmiName_RequestGetCoupon="RequestGetCoupon";
       
public const string RmiName_First = RmiName_RequestItemBuy;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_RequestItemBuy="";
public const string RmiName_RequestItemBuyNumber="";
public const string RmiName_RequestItemUse="";
public const string RmiName_RequestItemEquip="";
public const string RmiName_RequestItemUnEquip="";
public const string RmiName_RequestItemDelete="";
public const string RmiName_RequestItemDeleteNumber="";
public const string RmiName_RequestItemSell="";
public const string RmiName_RequestItemSellNumber="";
public const string RmiName_RequestItemProduce="";
public const string RmiName_RequestInvenvorySort="";
public const string RmiName_RequestQuestAccept="";
public const string RmiName_RequestQuestDelete="";
public const string RmiName_RequestQuestClear="";
public const string RmiName_RequestStatusUseStatPoint="";
public const string RmiName_RequestStatusUseSkillPoint="";
public const string RmiName_RequestDeleteQuickSlot="";
public const string RmiName_RequestSetQuickSlot="";
public const string RmiName_RequestGetCoupon="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

