 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace Net_Contact_S2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ReplyLoginCharacter = (Nettention.Proud.RmiID)1300+1;
			public const Nettention.Proud.RmiID ReplyLogoutCharacter = (Nettention.Proud.RmiID)1300+2;
			public const Nettention.Proud.RmiID ReplyChangeChannel = (Nettention.Proud.RmiID)1300+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ReplyLoginCharacter,
			ReplyLogoutCharacter,
			ReplyChangeChannel,
		};
	}
}
namespace Net_Behavior_S2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ReplyCharacterJoinMap = (Nettention.Proud.RmiID)1400+1;
			public const Nettention.Proud.RmiID ReplyCharacterJoinPublicPortal = (Nettention.Proud.RmiID)1400+2;
			public const Nettention.Proud.RmiID ReplyCharacterJoinPrivateMap = (Nettention.Proud.RmiID)1400+3;
			public const Nettention.Proud.RmiID ReplyCharacterJoinPrivatePortal = (Nettention.Proud.RmiID)1400+4;
			public const Nettention.Proud.RmiID ReplyCharacterExitPrivateMap = (Nettention.Proud.RmiID)1400+5;
			public const Nettention.Proud.RmiID ReplyPartyCreate = (Nettention.Proud.RmiID)1400+6;
			public const Nettention.Proud.RmiID ReplyPartyJoin = (Nettention.Proud.RmiID)1400+7;
			public const Nettention.Proud.RmiID ReplyPartyLeave = (Nettention.Proud.RmiID)1400+8;
			public const Nettention.Proud.RmiID ReplyPartySetState = (Nettention.Proud.RmiID)1400+9;
			public const Nettention.Proud.RmiID NotifyPartyAppointHost = (Nettention.Proud.RmiID)1400+10;
			public const Nettention.Proud.RmiID NotifyPartyJoinMember = (Nettention.Proud.RmiID)1400+11;
			public const Nettention.Proud.RmiID NotifyPartyLeaveMember = (Nettention.Proud.RmiID)1400+12;
			public const Nettention.Proud.RmiID NotifyPartyMemberKick = (Nettention.Proud.RmiID)1400+13;
			public const Nettention.Proud.RmiID NotifyRespawnEnermy = (Nettention.Proud.RmiID)1400+14;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ReplyCharacterJoinMap,
			ReplyCharacterJoinPublicPortal,
			ReplyCharacterJoinPrivateMap,
			ReplyCharacterJoinPrivatePortal,
			ReplyCharacterExitPrivateMap,
			ReplyPartyCreate,
			ReplyPartyJoin,
			ReplyPartyLeave,
			ReplyPartySetState,
			NotifyPartyAppointHost,
			NotifyPartyJoinMember,
			NotifyPartyLeaveMember,
			NotifyPartyMemberKick,
			NotifyRespawnEnermy,
		};
	}
}

				 
